# Generated by Django 5.2.8 on 2025-11-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('change', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('NBL', 'Nepal Bank Ltd.'), ('SCB', 'Standard Chartered'), ('NIC', 'NIC Asia Bank'), ('SHL', 'Soaltee Hotel'), ('NMB', 'NMB Bank'), ('CBL', 'Civil Bank')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=20)),
                ('is_gainer', models.BooleanField(default=True)),
            ],
        ),
    ]
