# Generated by Django 5.2.8 on 2025-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
