# Generated by Django 5.2.8 on 2025-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_nepseindex_nepseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(choices=[('NEPSE Index', 'NEPSE Index'), ('Sensitive Index', 'Sensitive Index'), ('Float Index', 'Float Index'), ('Sensitive Float Index', 'Sensitive Float Index'), ('Banking SubIndex', 'Banking SubIndex'), ('Development Bank', 'Development Bank'), ('Finance Index', 'Finance Index'), ('Hotels And Tourism', 'Hotels And Tourism'), ('Hydropower Index', 'Hydropower Index'), ('Insurance Index', 'Insurance Index'), ('Life Insurance', 'Life Insurance'), ('Non Life Insurance', 'Non Life Insurance'), ('Investment', 'Investment'), ('Manufacturing And Processing', 'Manufacturing And Processing')], db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('change_pct', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_indices',
                'ordering': ['-timestamp', 'index_name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_turnover', models.FloatField(blank=True, null=True)),
                ('total_traded_shares', models.FloatField(blank=True, null=True)),
                ('total_transactions', models.FloatField(blank=True, null=True)),
                ('total_scrips', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('float_market_cap', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_summary',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='nepseprice',
            options={'ordering': ['-timestamp', 'symbol']},
        ),
        migrations.AddIndex(
            model_name='nepseprice',
            index=models.Index(fields=['-timestamp'], name='nepse_price_timesta_50dee6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketindex',
            index=models.Index(fields=['index_name', '-timestamp'], name='market_indi_index_n_c862e9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketindex',
            index=models.Index(fields=['-timestamp'], name='market_indi_timesta_a97ee9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketindex',
            unique_together={('index_name', 'timestamp')},
        ),
    ]
