# Generated by Django 5.2.8 on 2025-12-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], db_index=True, max_length=4)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], db_index=True, default='COMPLETED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'symbol', '-created_at'], name='trades_user_id_e39a99_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', '-created_at'], name='trades_symbol_7d8c7c_idx'),
        ),
    ]
