# Generated by Django 5.2.8 on 2026-01-01 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_trade_delete_watchlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('PRE_OPEN', 'PRE_OPEN'), ('CONTINUOUS', 'CONTINUOUS'), ('CLOSED', 'CLOSED'), ('PAUSED', 'PAUSED')], default='CLOSED', max_length=15)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], db_index=True, max_length=4)),
                ('qty', models.PositiveIntegerField()),
                ('filled_qty', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PARTIAL', 'PARTIAL'), ('FILLED', 'FILLED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('executed_qty', models.PositiveIntegerField()),
                ('executed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_executions', to='myapp.order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_executions', to='myapp.order')),
            ],
            options={
                'db_table': 'trade_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'side', 'status', 'created_at'], name='orders_symbol_549e96_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', '-created_at'], name='orders_user_id_7789d4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'status'], name='orders_symbol_311ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'symbol'], name='portfolio_user_id_e737e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['symbol', '-executed_at'], name='trade_execu_symbol_ed7d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeexecution',
            index=models.Index(fields=['-executed_at'], name='trade_execu_execute_84a4f8_idx'),
        ),
    ]
