# Generated by Django 5.2.8 on 2026-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesticklesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
