# Generated by Django 5.2.8 on 2026-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_candlesticklesson_youtube_url_delete_usersettings'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='candlesticklesson',
        #     name='youtube_url',
        # ),
        migrations.AddField(
            model_name='customuser',
            name='buy_sell_notifications',
            field=models.BooleanField(default=True),
        ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='phone',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
