# Generated by Django 5.2.8 on 2026-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_candlesticklesson_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_currency',
            field=models.CharField(default='NPR', max_length=10),
        ),
    ]
