# Generated by Django 5.2.8 on 2026-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_customuser_default_currency'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='candlesticklesson',
        #     name='youtube_url',
        # ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='phone',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
    ]
