# Generated by Django 5.2.8 on 2026-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_candlesticklesson_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlesticklesson',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
