# Generated by Django 5.2.8 on 2026-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_candlesticklesson_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesticklesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
