# Generated by Django 5.2.8 on 2026-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_paymenttransaction_verification_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.IntegerField(default=1, help_text='1=Basic, 2=Premium, 3=Gold'),
        ),
    ]
