# Generated by Django 5.2.8 on 2026-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_add_quant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecommendation',
            name='market_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockrecommendation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
