# Generated by Django 5.2.8 on 2026-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_stockrecommendation_market_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsession',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
