# Generated by Django 5.2.8 on 2026-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_marketsession_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market'), ('STOP_LOSS', 'Stop Loss')], db_index=True, default='LIMIT', max_length=10),
        ),
    ]
