# Generated by Django 5.2.8 on 2026-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_marketsession_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pidx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
