# Generated by Django 5.2.8 on 2026-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_order_order_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecommendation',
            options={'ordering': ['-confidence', 'symbol']},
        ),
        migrations.AddField(
            model_name='stockrecommendation',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI Diagnostics and Model specific metadata'),
        ),
        migrations.AddField(
            model_name='stockrecommendation',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Signal expiry - defaults to next trading day', null=True),
        ),
        migrations.AlterField(
            model_name='stockrecommendation',
            name='trend',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral'), ('Bullish (Exhausted)', 'Bullish (Exhausted)'), ('Bearish (Reversal Possible)', 'Bearish (Reversal Possible)')], default='Neutral', max_length=100),
        ),
    ]
