# Generated by Django 5.2.8 on 2026-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_customuser_is_premium_paymenttransaction_pidx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(default='khalti', max_length=50),
        ),
    ]
