# Generated by Django 5.2.8 on 2026-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_sector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='stocks_sector_94dada_idx',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
