# Generated by Django 5.2.8 on 2026-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_stock_stocks_sector_94dada_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector_locked',
            field=models.BooleanField(default=False, help_text='If True, the scraper will not overwrite the sector.'),
        ),
    ]
