# Generated by Django 5.2.8 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_stock_sector_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='color_class',
            field=models.CharField(choices=[('sc-blue', 'Blue (Banks)'), ('sc-indigo', 'Indigo (Dev Banks)'), ('sc-purple', 'Purple (Microfinance)'), ('sc-violet', 'Violet (Finance)'), ('sc-teal', 'Teal (Investment)'), ('sc-orange', 'Orange (Hotels)'), ('sc-red', 'Red (Manufacturing)'), ('sc-cyan', 'Cyan (Hydropower)'), ('sc-green', 'Green (Life Insurance)'), ('sc-lime', 'Lime (Non-Life Insurance)'), ('sc-amber', 'Amber (Mutual Fund)'), ('sc-rose', 'Rose (Debentures)'), ('sc-pink', 'Pink (Trading)'), ('sc-gray', 'Gray (Others)')], default='sc-gray', help_text='CSS class for sector badge color', max_length=30),
        ),
    ]
