# Generated by Django 5.2.8 on 2026-03-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_paymenttransaction_gateway'),
        ('myapp', '0034_sector_color_class'),
    ]

    operations = [
    ]
