# Generated by Django 5.2.8 on 2026-03-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_merge_20260310_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='color_class',
        ),
    ]
