# Generated by Django 5.2.8 on 2026-04-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
