# Generated by Django 5.2.8 on 2026-04-11 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0038_alter_customuser_portfolio_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('virtual_balance__gte', 0)), name='virtual_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('portfolio_value__gte', 0)), name='portfolio_value_non_negative'),
        ),
    ]
